# Generated by Django 5.0.6 on 2024-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtext_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='video',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='file_name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='text',
            field=models.CharField(default='fdsa', max_length=1000),
            preserve_default=False,
        ),
    ]
