# Generated by Django 5.0.6 on 2024-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtext_app', '0002_remove_userrequest_video_userrequest_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='file_name',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
